### ISSUE TITLE
pulp psci hangs on Windows

### ISSUE THREAD

**Issue by alexchandel** [purescript-contrib/pulp#25] opened 2015-03-23 20:44 UTC
Running `pulp psci` on windows, in the Git Bash shell, causes pulp to hang indefinitely, never starting psci:

``` sh
$ pulp psci


```

`psci` is in my path at `/c/ProgramData/chocolatey/bin/psci`, and running `psci` works fine.

**Comment by hdgarrood** [comment] 2015-12-11 01:59
I think this might have been https://github.com/bodil/pulp/issues/121. Was there a `bower.json` file in the current directory? Does adding one stop this from happening?

**Comment by hdgarrood** [comment] 2015-12-16 14:19
Closing as a duplicate of #121.

**Closed as completed by hdgarrood** 2015-12-16 14:19 UTC
