### ISSUE TITLE
`ver` is undefined in `pulp init`

### ISSUE THREAD

**Issue by Fresheyeball** [purescript-contrib/pulp#53] opened 2015-07-15 18:51 UTC
``` bash
$ pulp init
blah\npm\node_modules\pulp\validate.js:7
    ver = ver.trim();
             ^
TypeError: Cannot read property 'trim' of undefined
    at blah\npm\node_modules\pulp\validate.js:7:14
    at ChildProcess.<anonymous> (blah\npm\node_modules
\pulp\exec.js:31:7)
    at ChildProcess.emit (events.js:107:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1072:12)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

$ psc --version
0.7.0.0

$ pulp --version
4.0.2
```

**Comment by stkb** [comment] 2015-07-15 19:30
Have this error too, since switching from the cabal installation of purescript to the npm package.

The problem is, on Windows, with the npm installation, `psc.exe` doesn't exist on the path, only `psc.cmd`. The `child_process.spawn("psc", ...)` code in pulp looks for a file named 'psc' (psc.exe would work), but it doesn't exist, meaning none of pulp works.

Using `child_process.exec()` would work though then you have to build the compete command string yourself.

**Comment by maiermic** [comment] 2015-07-18 08:02
I've this error as well on Windows with npm package of purescript.

Executables can be found in `%APPDATA%\Roaming\npm\node_modules\purescript\vendor\`. I copied them to `%APPDATA%\Roaming\npm\` to fix this error on my PC.

**Comment by bodil** [comment] 2015-07-18 08:58
Can anyone provide a PR? I don't have a Windows environment to figure this out in...

**Comment by maiermic** [comment] 2015-07-18 10:20
cabal only adds executables (e.g. `psc.exe`) and npm batch files with extension `cmd` (e.g. `psc.cmd`). Any idea how to check which file is available?

**Comment by stkb** [comment] 2015-07-18 12:35
I'd already worked on a fix for this, so can submit a PR. It's not very pretty, basically tries to execute `psc` and then if that's not found, tries `psc.cmd`

**Comment by bodil** [comment] 2015-07-18 12:36
I think that should be an acceptable solution.

**Closed as completed** 2015-07-25 19:05 UTC
