### ISSUE TITLE
easily overwrite some of the config options for `pulp server`

### ISSUE THREAD

**Issue by cdepillabout** [purescript-contrib/pulp#91] opened 2015-10-28 05:14 UTC
Is there a way to easily overwrite some of the config options for `pulp server` (webpack)?

It looks like the default config options are set in [`server.js`](https://github.com/bodil/pulp/blob/master/server.js#L30):

```
    var config = {
      cache: true,
      context: path.resolve(process.cwd(), "src"),
      entry: "./.webpack.js",
      debug: true,
      devtool: "source-map",
      output: {
        path: process.cwd(),
        pathinfo: true,
        filename: "app.js"
      },
      module: {
        loaders: [
          {
            test: /\.purs$/,
            loader: "purs-loader?output=" + buildPath +
                    "&" + sources.concat(ffis).join("&")
          }
        ]
      }, 
...
```

I would like to override `config.output` without changing the rest of the options.

I believe I could create my own `webpack.config.js` file and pass it to `pulp server` like this:

```
$ pulp server --config ./webpack.config.js
```

But I would need to duplicate the logic for computing the `sources` and `ffis` variables (used in `config.module.loaders[0].loader`) in my own `webpack.config.js`.  This seems very error prone.

Is there an easier way of overwriting just one or two of the config options?

**Comment by nwolverson** [comment] 2015-11-25 19:48
Does it make sense to merge a config into this instead of replacing it? 

_Edit_: though now that I say that I realise that I wanted to add a loader which isn't so obvious as merging object properties.

**Comment by cdepillabout** [comment] 2015-11-26 02:38
@nwolverson: It could definitely make sense to merge the config instead of replacing it.  However, I also wanted to change the `output` and `loaders` setting, so I was having a pretty tough time with it.

I posted a question question about it on StackOverflow:

http://stackoverflow.com/questions/33516671/how-to-componentize-purescript-halogen-application

The answer can be summed up as "use `gulp`".  `pulp` is really only for small libraries and simple applications.

If you look at a lot of slamdata's purescript libraries/projects, they are almost all using `gulp`.  `gulp` just gives you much more freedom about how/what you're building.

Here is an example `gulp` config that I'm using:

https://github.com/slamdata/purescript-halogen/issues/236

It's unfortunate that the Purescript book uses `pulp` instead of `gulp`.

**Comment by cdepillabout** [comment] 2015-11-26 02:45
@nwolverson: Also, it looks like `pulp` is being actively developed (there are multiple commits in the past month), but the majority of Github issues are just ignored.  Despite being recommended by the purescript book, I would really advise staying away from `pulp`, at least for the time being.

**Comment by hdgarrood** [comment] 2015-11-26 03:31
@cdepillabout If you want to use gulp that's fine, but to start telling people to stay away on the project's own issue tracker is pretty rude, I think. Surely you're aware that every comment gets sent to the maintainer as an email by default?

To be totally honest, I think if you'd just taken two minutes to look through the output of `pulp --help` or even the README in this repo, you would have realised that pulp is actually flexible enough for lots of use cases. I answered your stackoverflow question, by the way; pulp _does_ cover that specific use case.

I think you're right in that gulp is probably the best choice for the specific use case you've brought up here (for the time being). But I could hardly disagree more with your statement that it's unfortunate that the PureScript book uses `pulp` instead of `gulp`, or that it shouldn't be the default choice for PureScript projects. (I'm not interested in debating this here; I just wanted it on the record.)

**Comment by cdepillabout** [comment] 2015-11-26 04:31
@hdgarrood Thanks for the response!  I think it is a good counter-point to what I was saying.

> to start telling people to stay away on the project's own issue tracker is pretty rude

If I was starting out in purescript today, I would have wanted someone to tell me to stay away from `pulp` because it is inflexible.  In my case (and @nwolverson's case?), `pulp` is not flexible enough to do what I want to do.

If Github had some sort of private messaging functionality, my response may have been better as a private message.  However, making my response public makes it much easier to find by new Purescript developers.  Maybe my response would have been better as a blog post?

> To be totally honest, I think if you'd just taken two minutes to look through the output of `pulp --help` or even the `README` in this repo...

It makes me feel bad that you would assume this.  I actually spent a lot of time reading through a `pulp`'s source code making sure that it doesn't do what I need.  It's so much more mental effort to read code without type annotations.

Also, thanks for taking the time to respond to my StackOverflow question!

**Comment by nwolverson** [comment] 2015-11-26 07:49
Getting back to the issue, I was perfectly able to use `pulp` and specify my own webpack config, but it did require staring at pulp source code to find out what to put in it. So maybe an example config somewhere (or if there is one, adding a link to it) could be useful.

Actual change to pulp's behavior just useful if it's easy & simple.

**Comment by bodil** [comment] 2015-11-26 22:55
@cdepillabout, I think you're missing the point of Pulp entirely. Its intention is to provide sensible defaults for most everyday tasks a PS user will encounter. If you need something beyond this, you're advised to employ something like gulp-purescript. This is by design, not, as you suggest, a design flaw.

If you need Pulp issues resolved at a schedule convenient to you, you're welcome to pay me for my time.

I'd take suggestions for how this feature might be reasonably implemented. As mentioned, merging the default config with an external one doesn't seem like a good solution.

**Comment by cdepillabout** [comment] 2015-11-27 01:27
@nwolverson Would you be able to share the config you came up with?  I might be interested in using it for future projects.

**Comment by cdepillabout** [comment] 2015-11-27 01:50
@bodil Thanks for your response.

> [Pulp]'s intention is to provide sensible defaults for most everyday tasks a PS user will encounter. If you need something beyond this, you're advised to employ something like gulp-purescript. This is by design, not, as you suggest, a design flaw.

I think you're right.  Since `pulp` was introduced in the Purescript book, I had assumed that it could handle most situations, much like Haskell's `stack`.  I was surprised to find out that it couldn't.  I didn't want other new users to waste their time trying to use Pulp when it doesn't fit their use-case.

I guess it would be nice to have a "When to use Pulp / When to use Gulp" wiki page for people (like me) coming from Haskell with no real javascript experience.

> If you need Pulp issues resolved at a schedule convenient to you, you're welcome to pay me for my time.

I realize that Pulp is open source and developed for free.  Demanding that you implement new features with no renumeration is basically out of the question.

However, as a new user, it's unfortunate when no one comments on a issue I've created.  Even a super simple answer like "please send pull request", or "no, you're dumb lol" is much better than no comment.  It's hard to judge whether I'm doing something wrong, or the software isn't intended to be used like I'm trying to use it.

**Comment by hdgarrood** [comment] 2016-02-28 15:11
Given that we seem to have settled on the approach of setting up your own purs-loader/webpack config if `pulp server` is insufficient, I'm closing this.

**Closed as completed by hdgarrood** 2016-02-28 15:11 UTC
