### ISSUE TITLE
Passthrough options for `pulp run` are not working

### ISSUE THREAD

**Issue by adius** [purescript-contrib/pulp#318] opened 2017-12-22 18:07 UTC
```sh
$ pulp run -- path/to/file.txt
* Building project in /Users/adrian/Projects/example
Error found:
at path/to/file.txt line 3, column 18 - line 3, column 18

  Unable to parse module:
  unexpected "0"
  expecting end of character


See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.


* ERROR: Subcommand terminated with exit code 1
```

**Comment by hdgarrood** [comment] 2017-12-22 18:33
Thanks for the report! This is a duplicate of #309.

**Closed as completed by hdgarrood** 2017-12-22 18:33 UTC

**Comment by adius** [comment] 2017-12-22 19:06
Weird, I searched for similar issues, but didn't find any 😅.
Sorry for the duplicate...

**Comment by hdgarrood** [comment] 2017-12-22 19:32
No worries :) it's probably because I only just changed the title.
