### ISSUE TITLE
pulp should pass globs to psc-bundle instead of expanding them itself

### ISSUE THREAD

**Issue by LukaHorvat** [purescript-contrib/pulp#111] opened 2015-11-25 02:04 UTC
I'm running Windows 10.

The project I'm running is the AJAX example from the halogen library.

This is the command line session

```
C:\Users\Luka\Documents\Projects\WebHaskell\client>pulp browserify --to script.js
* Browserifying project in C:\Users\Luka\Documents\Projects\WebHaskell\client
* Building project in C:\Users\Luka\Documents\Projects\WebHaskell\client
psc: No files found using pattern: src/**/*.js
* Build successful.
* Bundling Javascript...
The command line is too long.
* ERROR: Subcommand terminated with error code 1
```

Same happens with `pulp build -O --to script.js`

This is kind of critical because currently my JS file is 900kb.

**Comment by hdgarrood** [comment] 2015-11-25 02:58
The problem is either [here](https://github.com/bodil/pulp/blob/a7af148f0cda9c5cdca375ee47947d5cd1cb42ae/exec.js#L59-L69) or [here](https://github.com/bodil/pulp/blob/a7af148f0cda9c5cdca375ee47947d5cd1cb42ae/browserify.js#L17) depending on your point of view. The problem is that pulp is expanding the glob itself rather than passing globs to `psc-bundle`.

Anyway, I think you can work around this by calling psc-bundle yourself: `psc-bundle 'output/**/*.js' > out.js` (or however you quote things on windows).

**Comment by LukaHorvat** [comment] 2015-11-25 10:04
While that works, browserify must to something extra because that 900kb JS file runs fine, but the bundled version doesn't. It complains about not knowing what `require` is (at runtime, in the Chrome console). 
Halogen does have some fishy dependency on the virtual-dom NPM module and it's its `require` that's failing, but browserify apparently doesn't have a problem with that. Any ideas?

**Comment by hdgarrood** [comment] 2015-11-25 12:32
`npm install virtual-dom` and use the `--node` flag for browserify?

**Comment by LukaHorvat** [comment] 2015-11-25 14:11
Thanks man! That worked.

**Comment by bodil** [comment] 2015-11-26 22:39
Not sure what's causing this, actually - @hdgarrood, the line in `browserify.js` you pointed to shouldn't actually be run given the command line that was being used. In fact, `psc-bundle` shouldn't be run at all (see #106). It'll be `build.js` invoking it in 5.0.0, though.

@LukaHorvat, can you test if this is still happening with version 5.0.1 (which I'm about to release in a few minutes)?

**Comment by LukaHorvat** [comment] 2015-11-27 08:44
`browserify` works but now outputs large files (I assume this is intended), but `pulp build -O --to ...` still fails the same way.

**Comment by hdgarrood** [comment] 2015-11-27 20:14
(Mainly just a note for me: this is fixed in the purescript port.)

**Closed as completed** 2015-12-16 14:18 UTC
