### ISSUE TITLE
'pulp server' fails on hello-server example

### ISSUE THREAD

**Issue by ktodyruik** [purescript-contrib/pulp#133] opened 2015-12-22 17:35 UTC
I am new, running on windows, and going through the pulp documentation "Launching a deveopment server".
https://github.com/bodil/pulp#launching-a-development-server

I get an error when running 'pulp server' on my hello server example.

Can anyone suggest what might be the problem here?

Thanks.
Kerry

```
λ pulp server
* Server listening on http://localhost:1337/
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn psc ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

C:\Sketchbook\Purescript\helloserver
```

**Comment by hdgarrood** [comment] 2015-12-22 17:41
Pulp expects the PureScript compiler psc to be on your path. Does running psc --version work?

**Comment by ktodyruik** [comment] 2015-12-22 17:43
Yes. It is on my path.

**Comment by hdgarrood** [comment] 2015-12-22 17:48
Hm, ok. Does pulp build work?

**Comment by ktodyruik** [comment] 2015-12-22 17:49
Yes.

```
C:\Sketchbook\Purescript\helloserver
λ psc --version
0.7.6.1

C:\Sketchbook\Purescript\helloserver
λ pulp build
* Project unchanged; skipping build step.

C:\Sketchbook\Purescript\helloserver
λ pulp psci
 ____                 ____            _       _
|  _ \ _   _ _ __ ___/ ___|  ___ _ __(_)_ __ | |_
| |_) | | | | '__/ _ \___ \ / __| '__| | '_ \| __|
|  __/| |_| | | |  __/___) | (__| |  | | |_) | |_
|_|    \__,_|_|  \___|____/ \___|_|  |_| .__/ \__|
                                       |_|

:? shows help
> :q
See ya!

C:\Sketchbook\Purescript\helloserver
λ

```

**Comment by hdgarrood** [comment] 2015-12-22 18:11
Ok, good. What does pulp --version give you?

**Comment by ktodyruik** [comment] 2015-12-22 18:15
```
λ pulp --version
6.1.0
```

**Comment by hdgarrood** [comment] 2015-12-22 20:58
Well that is really weird. pulp server shouldn't even be calling spawn...

**Comment by hdgarrood** [comment] 2015-12-25 00:21
I'm trying to reproduce this, and I haven't been able to. I think it's failing inside `purs-loader`: https://github.com/ethul/purs-loader/blob/master/src/PursLoader/Loader.purs#L106

I have no idea how it could have disappeared off your path between calling pulp and webpack calling purs-loader, though. Maybe webpack is fiddling with the environment.

Perhaps you can investigate by installing pulp locally, and modifying the code around where psc gets spawned by purs-loader so that it prints some diagnostic information (like your PATH, for instance)?

**Comment by tangmi** [comment] 2016-01-19 00:59
The error is definitely happening in `purs-loader`. It's most likely because Windows is super wacky and [can't run `.bat` or `.cmd` files without their own terminal using `spawn`](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows), and `psc` is a batch script on Windows (?).

There's a potential fix here: https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-3220048

``` js
spawn('psc', ['--version'], {
    stdio: 'inherit',
});

// events.js:141
//   throw er; // Unhandled 'error' event
//   ^
//
// Error: spawn psc ENOENT
//   ... etc ...
```

``` js
spawn('cmd', [
    '/s',
    '/c',
    'psc --version'
], {
    windowsVerbatimArguments: true,
    stdio: 'inherit',
});
// => 0.7.6.1
```

It's super gross, but one could switch based off `process.platform == 'win32'`

Note that this comment isn't meant to be helpful, since I don't have any suggestions on what to do, as the "correct" fix, I think, is to change `child_process` itself (and that is already being tracked in the link above).

EDIT: Just realized that @hdgarrood is a maintainer of `purescript-node-child-process`. This "fix" _could_ go there and this may be solved for everyone (including `purs-loader` if https://github.com/ethul/purs-loader/issues/35 gets closed.)

**Comment by hdgarrood** [comment] 2016-01-19 01:20
Oh of course! Yes, that does look like what is happening. We handled this inside pulp by checking `process.platform`, and retrying failed commands with `.cmd` appended to the executable name: https://github.com/bodil/pulp/blob/e9e1e178a578498e04b2887f447eb82c7041a296/src/Pulp/Exec.purs#L126-L139

Looking at https://github.com/ethul/purs-loader/blob/94cc1cdd03b9c2115813a698b1e4337bce894321/src/PursLoader/Loader.purs, it seems `purs-loader` is always calling `spawn` with `psc`, so appending `.cmd` would probably fix it.

I think we do always need to try both with and without `.cmd`, though: if you install purescript from source you end up with a `psc.exe`, whereas if you use the npm package, you'll get a `psc.cmd`.

Given how long that issue on node has been open for, I think it's probably sensible to work around it rather than wait for it to be addressed. I didn't read all of the comments but it seems like it's been quite difficult to even agree on what the ideal behaviour would be.

/cc @ethul

**Comment by hdgarrood** [comment] 2016-01-19 01:29
I'm not keen on putting a workaround inside `purescript-node-child-process`, sorry. That library is meant to be a minimal wrapper, as close as is reasonably possible to the underlying node API. If we're going to start doing this kind of stuff, I'd rather it were in a separate library, perhaps which builds on top of `node-child-process`.

**Comment by hdgarrood** [comment] 2016-01-19 01:33
Additionally, my impression is that part of the reason that issue has been open for so long is that it's an awkward problem without an obvious fix. I worry that if we tried to fix it, we might introduce new problems. At least the current set of problems is fairly well understood and googlable; by comparison, any problems we might introduce would not be.

**Comment by tangmi** [comment] 2016-01-19 02:11
That's more than fair--It seems that this workaround may have some issues regarding interacting with the `spawn`ed process (such as sending signals, etc) https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-10549609

One of the comments (or referenced comments) suggests using [`node-cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) as a cross-platform solution.

**Comment by ethul** [comment] 2016-01-19 03:01
We had this issue in purescript-contrib/gulp-purescript#30, and decided to go with [cross-spawn](https://www.npmjs.com/package/cross-spawn) as the fix. I will raise an issue to use that for the `purs-loader`. However, I will be merging ethul/purs-loader#34 soon, so the fix will go in the [purescript-webpack-plugin](https://www.npmjs.com/package/purescript-webpack-plugin), since that will be running `psc` and `psc-bundle`.

**Comment by hdgarrood** [comment] 2016-02-02 11:56
I think the right way to address this is #151, so I'm going to close this as a duplicate of that.

**Closed as completed by hdgarrood** 2016-02-02 11:56 UTC

**Comment by UrKr** [comment] 2016-03-01 00:06
I'm on windows 10 64bit and I'm still getting this error after running pulp server. 

pulp -v
Pulp version 8.1.0

node -v
v5.7.0

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn psc ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

**Comment by hdgarrood** [comment] 2016-03-01 00:26
Now that this is fixed in purs-loader, I think the fix is to update the version of purs-loader that pulp depends on (as a temporary solution before we address #151).

In the meantime, if a dev server is important to you, I'd use webpack directly as described at https://www.npmjs.com/package/purs-loader. All the other pulp commands should work fine in the meantime, too.

**Comment by UrKr** [comment] 2016-03-01 08:36
Thanks for the reply!
